[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RF_app"
authors = [{name = "Daniel Bolfeta", email = "cesarbolfeta@yahoo.com"}]
readme = "README.md"
dynamic = ["version", "description"]

[project.urls]
Home = "http://github.com/Cbolfeta"
